name: Build LaTeX document
on: [push]
permissions: 
  contents: write
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v4
        with:
          root_file: card.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: card.pdf

      - name: Update Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/') != true 
        with:
          tag_name: latest 
          files: card.pdf 
          draft: false
          prerelease: false
          name: "Last version"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}